# Created using winget-create
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: M-Igashi.headroom
PackageVersion: 1.2.0
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: headroom.exe
    PortableCommandAlias: headroom
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/M-Igashi/headroom/releases/download/v1.2.0/headroom-v1.2.0-windows-x86_64.zip
    InstallerSha256: ""
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Gyan.FFmpeg
ManifestType: installer
ManifestVersion: 1.6.0
